Setup codebase
Derick1530/Hello-Microverse pull request #1
Opened 2023-01-10 11:31 UTC by Derick1530

- added a `.gitignore`
- added `node_modules` and `test.md` to gitignore file
- Set up a linter for HTML and CSS
- added `index.html`  `style.css`  and `test.md`

2023-01-10 11:40 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Derick1530 👋 

First of all, Congratulations on making it to Microverse 🥳 Welcome to the team 👏 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Descriptive pull request description ✔️ 
* .gitignore is setup correctly 💯 

## Required Changes:

- [ ] Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" or "linters are added" ... etc 👍 

_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 11:40 UTC, ha-manel commented on README.md
> +## Built With
- [ ] Please use the latest [README file version](https://github.com/microverseinc/readme-template) provided by Microverse and fill out all the required sections with information about your project (please don't leave the sections empty or with only placeholder text) to have a more professional documentation structure 💯

2023-01-10 15:23 UTC, ichala requested changes
Hi Student
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Correct Template used  ✔️ 


 ## Required Changes ♻️

- [ ] **_🛑  Check The Comments Below_**





## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 15:23 UTC, ichala commented on README.md
> +
- [ ] Good Job adding the correct readme template, however, as mentioned by the previous reviewer, kindly add your project information in the correct sections of the readme file, currently you just copied the template and updated some sections , please update all of them to make it professional 💯

2023-01-10 15:27 UTC, Derick1530 commented on README.md
> +
I don't quite get it, How can I do that?? there is some information I don't know what to fill in  @ichala

2023-01-10 16:03 UTC, ichala commented on README.md
> +
Well some of the sections for example the live link section , you don't need it in this project , so its okay to remove it from the readme file , so generally try to fill all necessary sections and the one that doesn't connect to your project you can remove them 🙏

2023-01-10 16:38 UTC, osamaashraf6 requested changes
Hi  @Derick1530 ☺️, 


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![ItsJustATinyChangeSheaWhitneyGIF](https://user-images.githubusercontent.com/83360636/211609489-1d465ea3-27b7-4ed0-b533-40a7657eb825.gif)

## Highlights ✔️
- [x] Good commit messages.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 16:38 UTC, osamaashraf6 commented on README.md
> +-->
- [ ]  Great job 😃 at adding the changes ♻️and updating some sections from the README file, but As stated by the previous reviewer☺️, kindly update the README file here it is not necessary to leave these comments in the file💯, so please it will be better if you remove the comments.

2023-01-10 16:38 UTC, osamaashraf6 commented on README.md
> +You don't need to install this application
- [ ] You did a great 👌job at updating the README file😊, but you said there was no installation😃, but I think there is an installation of the project like the node modules because you put the node modules at the gitignore💯, so kindly edit this part by saying to install 🪄 the project you need to install the ```npm i``` to install the node modules for the linter and any other modules.⤵️

2023-01-10 16:38 UTC, osamaashraf6 commented on README.md
> +
- [ ] You updated the README well😃 as stated by the previous reviewer, but I think you forgot here to add the LICENCE file👌 I think it is broken, so please try to put the correct MIT💯 file because when I try to open it redirects me to the page not found🐛, but don't worry you are almost there.

2023-01-10 17:10 UTC, Derick1530 commented
I've fixed all the requested changes, can you review again??? Thank you

On Tue, Jan 10, 2023 at 7:38 PM Osama Ashraf ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Derick1530 <https://github.com/Derick1530> ☺️,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't been addressed yet.
>
> [image: ItsJustATinyChangeSheaWhitneyGIF]
> <https://user-images.githubusercontent.com/83360636/211609489-1d465ea3-27b7-4ed0-b533-40a7657eb825.gif>
> Highlights ✔️
>
>    - Good commit messages.
>    - No linter errors. 💯
>    - Good usage in correcting GitHub flow
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
>    - N/A
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/Derick1530/Hello-Microverse/pull/1#discussion_r1065987474>
> :
>
> > +
>
> +<!--
>
> +HOW TO USE:
>
> +This is an example of how you may give instructions on setting up your project locally.
>
> +
>
> +Modify this file to match your project and remove sections that don't apply.
>
> +
>
> +REQUIRED SECTIONS:
>
> +- Table of Contents
>
> +- About the Project
>
> +  - Built With
>
> +  - Live Demo
>
> +- Getting Started
>
> +- Authors
>
> +- Future Features
>
> +- Contributing
>
> +- Show your support
>
> +- Acknowledgements
>
> +- License
>
> +
>
> +OPTIONAL SECTIONS:
>
> +- FAQ
>
> +
>
> +After you're finished please remove all the comments and instructions!
>
> +-->
>
>
>
>    - Great job 😃 at adding the changes ♻️and updating some sections from
>    the README file, but As stated by the previous reviewer☺️, kindly
>    update the README file here it is not necessary to leave these comments in
>    the file💯, so please it will be better if you remove the comments.
>
> ------------------------------
>
> In README.md
> <https://github.com/Derick1530/Hello-Microverse/pull/1#discussion_r1065996990>
> :
>
> > +### Install
>
> +
>
> +You don't need to install this application
>
>
>
>    - You did a great 👌job at updating the README file😊, but you said
>    there was no installation😃, but I think there is an installation of
>    the project like the node modules because you put the node modules at the
>    gitignore💯, so kindly edit this part by saying to install 🪄 the
>    project you need to install the npm i to install the node modules for
>    the linter and any other modules.⤵️
>
> ------------------------------
>
> In README.md
> <https://github.com/Derick1530/Hello-Microverse/pull/1#discussion_r1066003046>
> :
>
> > +<!-- LICENSE -->
>
> +
>
> +## 📝 License <a name="license"></a>
>
> +
>
> +This project is [MIT](./LICENSE) licensed.
>
> +
>
>
>
>    - You updated the README well😃 as stated by the previous reviewer,
>    but I think you forgot here to add the LICENCE file👌 I think it is
>    broken, so please try to put the correct MIT💯 file because when I try
>    to open it redirects me to the page not found🐛, but don't worry you
>    are almost there.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Derick1530/Hello-Microverse/pull/1#pullrequestreview-1242578668>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOYCTR5UCMWHH3YYKCKW7H3WRWGA3ANCNFSM6AAAAAATWUMWKU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-10 17:12 UTC, Derick1530 commented on README.md
> +
solved

2023-01-10 17:12 UTC, Derick1530 commented on README.md
> +You don't need to install this application
solved

2023-01-11 07:52 UTC, levy002 approved these changes
## Hello @Derick1530 
### I'm Levy, your PR reviewer

 Excellent, you nailed it :sunglasses: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights
- Good job for using correct git-flow :heavy_check_mark: 
- All linters are passing :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 08:01 UTC, merged